version: '3'
name: postgresql
services:

  postgres:
    container_name: PostgreSQL
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ASUS
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  adminer:
    container_name: Adminer
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080