version: '3'

services:

  database:
    image: postgres
    restart: always
    container_name: PostgreSQL
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ASUS
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: Adminer
    depends_on:
      - database
    ports:
      - 8080:8080